project_id = "fztiznsyknofxoplyirz"

[functions.ai-job-assistant]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-job-alerts]
verify_jwt = false

[functions.send-promotional-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.generate-magic-link]
verify_jwt = false

[functions.verify-magic-token]
verify_jwt = false
